Repository mapbox/mapbox-android-demo, pull requests merged in 2018-10, with the labels that each got.

#860 Basic Kotlin version of plain map
  MapboxAndroidDemo/build.gradle
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/basics/KotlinSimpleMapViewActivity.kt
  MapboxAndroidDemo/src/main/res/layout/activity_basic_simple_kotlin.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
  build.gradle
  gradle/dependencies.gradle
Labels: new example :sparkles:, ✓ ready for review :+1:

#872 Add kotlin circle layer example
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/KotlinStyleCirclesCategoricallyActivity.kt
  MapboxAndroidDemo/src/main/res/layout/activity_dds_kotlin_style_circles_categorically.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
Labels: enhancement :heavy_plus_sign:

#865 Rainfall data example tweaks
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/AddRainFallStyleActivity.java
Labels: refactor :recycle:, ✓ ready for review :+1:

#869 Variable rename in style fade switch example
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/StyleFadeSwitchActivity.java
Labels: enhancement :heavy_plus_sign:, ✓ ready for review :+1:

#879 Fix to local style JSON load example
  MapboxAndroidDemo/src/main/assets/local_style_file.json
  MapboxAndroidDemo/src/main/res/layout/activity_style_local_style_source.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: bug :bug:, ✓ ready for review :+1:

#886 Magic Window Demo
  MapboxAndroidDemo/build.gradle
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/MagicWindowKotlinActivity.kt
  MapboxAndroidDemo/src/main/res/layout/activity_magic_window.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/strings.xml
  MapboxAndroidDemo/src/main/res/values/system_and_random_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: kotlin, new example :sparkles:, ✓ ready for review :+1:

#786 Gradle-git version version bump to fix repo zip folder download issue
  gradle/script-git-version.gradle
Labels: :warning: DO NOT MERGE :warning:, work in progress :building_construction:
