Repository mapbox/mapbox-android-demo, pull requests merged in 2018-09, with the labels that each got.

#843 User Location on a Map Fragment
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/LocationPluginFragmentActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_user_location_map_frag.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
  scripts/exclude-activity-gen.json
Labels: new example :sparkles:

#851 Slowed down zoom speed for style fade switch
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/StyleFadeSwitchActivity.java
Labels: enhancement :heavy_plus_sign:, ✓ ready for review :+1:

#853 added null check to calendar integration example
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/CalendarIntegrationActivity.java
Labels: crash :boom:, ✓ ready for review :+1:

#845 Adding line background highlight example
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/assets/brussels_station_exits.geojson
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/query/HighlightedLineActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_query_highlighted_line.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#818 Data-driven styling temperature expression example
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/assets/weather_data_per_state_before2006.geojson
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/ExpressionIntegrationActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_dds_temperature_change.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#859 6.5.0 release
  CHANGELOG.md
  MapboxAndroidDemo/src/gpservices/play/en-US/whatsnew
Labels: :warning: DO NOT MERGE :warning:

#867 Docker image update
  circle.yml
  gradle/dependencies.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ✓ ready for review :+1:
