Repository mapbox/mapbox-android-demo, pull requests merged in 2018-08, with the labels that each got.

#799 Renamed LA tourism example
  MapboxAndroidDemo/src/gpservices/AndroidManifest.xml
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/PulsingLayerOpacityColorActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_lab_pulsing_layer_opacity_color.xml
  MapboxAndroidDemo/src/main/res/values-ca/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values-ca/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values-ca/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values-vi/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
  scripts/exclude-activity-gen.json
Labels: starter-task

#823 Fix color in ShowHideLayersActivity
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/ShowHideLayersActivity.java
Labels: bug :bug:, ✓ ready for review :+1:

#825 Add lifecycle method calls to the map used in the MarathonExtrusionActivity
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/extrusions/MarathonExtrusionActivity.java
Labels: ✓ ready for review :+1:

#827 Set content for PulsingLayerOpacityActivity
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/PulsingLayerOpacityColorActivity.java
Labels: bug :bug:, crash :boom:, ✓ ready for review :+1:

#822 Proguard rules fix/addition
  MapboxAndroidDemo/proguard-rules.pro
Labels: bug :bug:, ✓ ready for review :+1:

#792 Calendar content provider integration example
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/CalendarIntegrationActivity.java
  MapboxAndroidDemo/src/main/res/drawable-hdpi/calendar_event_icon.png
  MapboxAndroidDemo/src/main/res/drawable-mdpi/calendar_event_icon.png
  MapboxAndroidDemo/src/main/res/drawable-xhdpi/calendar_event_icon.png
  MapboxAndroidDemo/src/main/res/drawable-xxhdpi/calendar_event_icon.png
  MapboxAndroidDemo/src/main/res/drawable-xxxhdpi/calendar_event_icon.png
  MapboxAndroidDemo/src/main/res/layout/activity_calendar_content_provider.xml
  MapboxAndroidDemo/src/main/res/layout/calendar_rv_card.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#829 Maps SDK bump to 6.4.0
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:

#830 Marathon route 404 fix
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/extrusions/MarathonExtrusionActivity.java
Labels: bug :bug:, ✓ ready for review :+1:

#831 Static image demo fix
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/StaticImageActivity.java
Labels: bug :bug:, ✓ ready for review :+1:

#820 Transparent background + video example
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/TransparentBackgroundActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_style_transparent_render_background.xml
  MapboxAndroidDemo/src/main/res/raw/moving_background_water.mp4
  MapboxAndroidDemo/src/main/res/raw/no_bg_style.json
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:
