Repository mapbox/mapbox-android-demo, pull requests merged in 2018-06, with the labels that each got.

#732 Localization plugin camera change
  MapboxAndroidDemo/src/main/res/layout/activity_localization_plugin.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
Labels: enhancement :heavy_plus_sign:

#739 Added bathymetry example
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/assets/bathymetry-data.geojson
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/BathymetryActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_bathymetry.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#743 Location layer plugin tweaks
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/LocationPluginActivity.java
  gradle/dependencies.gradle
Labels: performance :dash:

#738 Added minimal InfoWindow with symbol layer example
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/assets/boston_police_stations.geojson
  MapboxAndroidDemo/src/main/assets/sf_poi.geojson
  MapboxAndroidDemo/src/main/assets/us_west_coast.geojson
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/InfoWindowSymbolLayerActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/SymbolLayerMapillaryActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_info_window_symbol_layer.xml
  MapboxAndroidDemo/src/main/res/layout/mapillary_layout_callout.xml
  MapboxAndroidDemo/src/main/res/layout/symbol_layer_info_window_layout_callout.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#747 Tweaks to Localization Plugin example
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/LocalizationPluginActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_localization_plugin.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: bug :bug:, ✓ ready for review :+1:

#745 Adding geocoding example
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/GeocodingActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_javaservices_geocoding.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#752 Correct fill layer expression for local json, vector source data mix
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/ChoroplethJsonVectorMixActivity.java
Labels: bug :bug:, ✓ ready for review :+1:

#757 Color to rgb expression fixes
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/BathymetryActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/ChoroplethZoomChangeActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/StyleCirclesCategoricallyActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/StyleLineIdentityPropertyActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/extrusions/PopulationDensityExtrusionActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/ZoomDependentFillColorActivity.java
Labels: bug :bug:

#748 Adding "snaking" directions route example
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/SnakingDirectionsRouteActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_javaservices_snaking_directions_route.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#746 added example of "search in this area" button
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/query/RedoSearchInAreaActivity.java
  MapboxAndroidDemo/src/main/res/drawable-hdpi/school_icon.png
  MapboxAndroidDemo/src/main/res/drawable-mdpi/school_icon.png
  MapboxAndroidDemo/src/main/res/drawable-xhdpi/school_icon.png
  MapboxAndroidDemo/src/main/res/drawable-xxhdpi/school_icon.png
  MapboxAndroidDemo/src/main/res/drawable-xxxhdpi/school_icon.png
  MapboxAndroidDemo/src/main/res/layout/activity_basic_simple_mapview.xml
  MapboxAndroidDemo/src/main/res/layout/activity_query_redo_search_in_area.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#761 Update tweaks to geojson clustering example
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/GeoJsonClusteringActivity.java
  MapboxAndroidDemo/src/main/res/drawable/ic_cross.xml
Labels: enhancement :heavy_plus_sign:, ✓ ready for review :+1:

#762 RecyclerView + map change to source/layer
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/RecyclerViewOnMapActivity.java
Labels: enhancement :heavy_plus_sign:, ✓ ready for review :+1:

#766 Fix to SymbolLayer + mapillary example
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/SymbolLayerMapillaryActivity.java
Labels: bug :bug:, work in progress :building_construction:
