Repository mapbox/mapbox-android-demo, pull requests merged in 2018-12, with the labels that each got.

#931 Update to issue template
  ISSUE_TEMPLATE.md
Labels: documentation :memo:, ✓ ready for review :+1:

#922 Adding background fog example
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/MapFogBackgroundActivity.java
  MapboxAndroidDemo/src/main/res/drawable/fog_background_gradient.xml
  MapboxAndroidDemo/src/main/res/layout/activity_map_fog_background.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#864 Adding Tilequery API example
  MapboxAndroidDemo/build.gradle
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/TilequeryActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_javaservices_tilequery.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
  gradle/dependencies.gradle
Labels: new example :sparkles:, starter-task, ✓ ready for review :+1:

#932 Add demos that could be used in China flavor
  MapboxAndroidDemo/build.gradle
  MapboxAndroidDemo/src/china/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/china/res/layout/activity_animated_image_gif.xml
  MapboxAndroidDemo/src/china/res/layout/activity_annotation_animated_marker.xml
  MapboxAndroidDemo/src/china/res/layout/activity_annotation_custom_marker.xml
  MapboxAndroidDemo/src/china/res/layout/activity_annotation_marker.xml
  MapboxAndroidDemo/src/china/res/layout/activity_annotation_polygon.xml
  MapboxAndroidDemo/src/china/res/layout/activity_basic_simple_kotlin.xml
  MapboxAndroidDemo/src/china/res/layout/activity_basic_symbol_layer.xml
  MapboxAndroidDemo/src/china/res/layout/activity_building_plugin.xml
  MapboxAndroidDemo/src/china/res/layout/activity_camera_animate.xml
  MapboxAndroidDemo/src/china/res/layout/activity_camera_bounding_box.xml
  MapboxAndroidDemo/src/china/res/layout/activity_camera_restrict.xml
  MapboxAndroidDemo/src/china/res/layout/activity_extrusion_light.xml
  MapboxAndroidDemo/src/china/res/layout/activity_extrusion_rotation.xml
  MapboxAndroidDemo/src/china/res/layout/activity_image_source.xml
  MapboxAndroidDemo/src/china/res/layout/activity_image_source_time_lapse.xml
  MapboxAndroidDemo/src/china/res/layout/activity_info_window_symbol_layer.xml
  MapboxAndroidDemo/src/china/res/layout/activity_lab_indoor_map.xml
  MapboxAndroidDemo/src/china/res/layout/activity_lab_marker_following_route.xml
  MapboxAndroidDemo/src/china/res/layout/activity_lab_pulsing_layer_opacity_color.xml
  MapboxAndroidDemo/src/china/res/layout/activity_lab_recycler_view_on_map.xml
  MapboxAndroidDemo/src/china/res/layout/activity_lab_space_station_location.xml
  MapboxAndroidDemo/src/china/res/layout/activity_localization_plugin.xml
  MapboxAndroidDemo/src/china/res/layout/activity_location_component.xml
  MapboxAndroidDemo/src/china/res/layout/activity_multiple_geometries.xml
  MapboxAndroidDemo/src/china/res/layout/activity_multiple_heatmap_styling.xml
  MapboxAndroidDemo/src/china/res/layout/activity_offline_manager.xml
  MapboxAndroidDemo/src/china/res/layout/activity_offline_simple.xml
  MapboxAndroidDemo/src/china/res/layout/activity_picture_in_picture.xml
  MapboxAndroidDemo/src/china/res/layout/activity_places_plugin.xml
  MapboxAndroidDemo/src/china/res/layout/activity_query_building_outline.xml
  MapboxAndroidDemo/src/china/res/layout/activity_query_feature.xml
  MapboxAndroidDemo/src/china/res/layout/activity_query_feature_count.xml
  MapboxAndroidDemo/src/china/res/layout/activity_query_highlighted_line.xml
  MapboxAndroidDemo/src/china/res/layout/activity_query_redo_search_in_area.xml
  MapboxAndroidDemo/src/china/res/layout/activity_query_select_building.xml
  MapboxAndroidDemo/src/china/res/layout/activity_style_add_wms_source.xml
  MapboxAndroidDemo/src/china/res/layout/activity_style_color_switcher.xml
  MapboxAndroidDemo/src/china/res/layout/activity_style_geojson_layer_in_stack.xml
  MapboxAndroidDemo/src/china/res/layout/activity_style_language_switch.xml
  MapboxAndroidDemo/src/china/res/layout/activity_style_line.xml
  MapboxAndroidDemo/src/china/res/layout/activity_style_line_layer.xml
  MapboxAndroidDemo/src/china/res/layout/activity_style_zoom_dependent_fill_color.xml
  MapboxAndroidDemo/src/china/res/layout/activity_symbol_layer_mapillary.xml
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:

#935 Java SDK 4.3.0 bump
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:
