Repository mapbox/mapbox-android-demo, pull requests merged in 2019-05, with the labels that each got.

#1029 Isochrone API refactor to use Java SDK wrapper
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/IsochroneActivity.java
Labels: refactor :recycle:, ✓ ready for review :+1:

#1054 Adding multiple color formatting to TextFieldMultipleFormatsActivity
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/TextFieldMultipleFormatsActivity.java
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: enhancement :heavy_plus_sign:, ✓ ready for review :+1:

#1041 Updated Mapbox SF office coordinates for PlacesPluginActivity
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/PlacesPluginActivity.java
Labels: refactor :recycle:, ✓ ready for review :+1:

#1062 Bumped Java SDK turf and services to 4.8.0
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:

#1039 Adding example of using TurfTransformation#circle to create visual ring
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/TurfRingActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_lab_hollow_circle.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#1030 Refactoring and splitting basic SymbolLayer icon examples
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/BasicSymbolLayerActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/IconSizeChangeOnClickActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_style_basic_symbol_layer.xml
  MapboxAndroidDemo/src/main/res/layout/activity_style_symbol_icon_size_change_on_click.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: refactor :recycle:, ✓ ready for review :+1:

#1049 Switching to greater than or equals for circle clustering example
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/CircleLayerClusteringActivity.java
Labels: refactor :recycle:, ✓ ready for review :+1:

#1063 Adding example of ignorePlacement/allowOverlap for text and icons
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/SymbolCollisionDetectionActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_dds_symbol_collision.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:

#1065 Adding coordinate check in IsochroneActivity
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/IsochroneActivity.java
Labels: crash :boom:, ✓ ready for review :+1:

#1064 Camera adjustment to GeojsonLayerInStackActivity
  MapboxAndroidDemo/src/main/res/layout/activity_style_geojson_layer_in_stack.xml
Labels: refactor :recycle:, ✓ ready for review :+1:

#1012 Tile loading performance measurement
  MapboxAndroidDemo/src/china/java/com/mapbox/mapboxandroiddemo/MapboxApplication.java
  MapboxAndroidDemo/src/global/AndroidManifest.xml
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MapboxApplication.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/utils/TileLoadingInterceptor.java
  MapboxAndroidWearDemo/src/main/AndroidManifest.xml
Labels: ✓ ready for review :+1:

#1073 Fix StringIndexOutOfBoundsException
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/utils/TileLoadingInterceptor.java
Labels: bug :bug:

#1031 Adjusted HomeScreenWidgetActivity class' location and its javadocs
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/HomeScreenWidgetActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/HomeScreenWidgetActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/utils/DemoAppHomeScreenAddressWidget.java
  scripts/exclude-activity-gen.json
Labels: new example :sparkles:, refactor :recycle:, ✓ ready for review :+1:

#1033 Adding ignore sign in button
  MapboxAndroidDemo/src/china/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/account/LandingActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/utils/SettingsDialogView.java
  MapboxAndroidDemo/src/main/res/layout/activity_landing.xml
  MapboxAndroidDemo/src/main/res/layout/settings_dialog_layout.xml
  MapboxAndroidDemo/src/main/res/menu/menu_activity_drawer.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/system_and_random_strings.xml
  SharedCode/src/main/java/com/mapbox/mapboxandroiddemo/commons/AnalyticsTracker.java
  SharedCode/src/main/java/com/mapbox/mapboxandroiddemo/commons/StringConstants.java
Labels: enhancement :heavy_plus_sign:, refactor :recycle:

#1070 Adding example of onStyleImageMissing listener usage
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/MissingIconActivity.java
  MapboxAndroidDemo/src/main/res/drawable-hdpi/antony.png
  MapboxAndroidDemo/src/main/res/drawable-hdpi/carlos.png
  MapboxAndroidDemo/src/main/res/drawable-hdpi/luciana.png
  MapboxAndroidDemo/src/main/res/drawable-hdpi/maria.png
  MapboxAndroidDemo/src/main/res/drawable-mdpi/antony.png
  MapboxAndroidDemo/src/main/res/drawable-mdpi/carlos.png
  MapboxAndroidDemo/src/main/res/drawable-mdpi/luciana.png
  MapboxAndroidDemo/src/main/res/drawable-mdpi/maria.png
  MapboxAndroidDemo/src/main/res/drawable-xhdpi/antony.png
  MapboxAndroidDemo/src/main/res/drawable-xhdpi/carlos.png
  MapboxAndroidDemo/src/main/res/drawable-xhdpi/luciana.png
  MapboxAndroidDemo/src/main/res/drawable-xhdpi/maria.png
  MapboxAndroidDemo/src/main/res/drawable-xxhdpi/antony.png
  MapboxAndroidDemo/src/main/res/drawable-xxhdpi/carlos.png
  MapboxAndroidDemo/src/main/res/drawable-xxhdpi/luciana.png
  MapboxAndroidDemo/src/main/res/drawable-xxhdpi/maria.png
  MapboxAndroidDemo/src/main/res/drawable-xxxhdpi/antony.png
  MapboxAndroidDemo/src/main/res/drawable-xxxhdpi/carlos.png
  MapboxAndroidDemo/src/main/res/drawable-xxxhdpi/luciana.png
  MapboxAndroidDemo/src/main/res/drawable-xxxhdpi/maria.png
  MapboxAndroidDemo/src/main/res/layout/activity_styles_missing_icon.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#1019 Maps SDK v7.4.0
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:

#1066 Variable label placement example
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/assets/poi_places.geojson
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/VariableLabelPlacementActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_style_variable_text_placement.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#1050 Adding example of "revealed" polygon hole with outline
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/assets/downtown_san_jose_hole.geojson
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/RevealedPolygonHoleOutlineActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_polygon_holes_outline_revealed.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#1084 Making needed iconTranslate -> iconOffset refactoring changes
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/ImageClusteringActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/ValueAnimatorIconAnimationActivity.java
Labels: refactor :recycle:, ✓ ready for review :+1:

#983 Adding draw on map for search example
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/assets/albuquerque_locations.geojson
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/query/FingerDrawQueryActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_finger_drag_draw.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:
