Repository mapbox/mapbox-android-demo, pull requests merged in 2019-04, with the labels that each got.

#996 bump Mapbox Maps SDK for Android to v7.3.0
  build.gradle
  gradle/dependencies.gradle
Labels: work in progress :building_construction:

#933 Adding rotating camera example
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/camera/SlowlyRotatingCameraActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_camera_slow_spin.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#934 Animated SymbolLayer icon movement example (pin drop)
  MapboxAndroidDemo/build.gradle
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/ValueAnimatorIconAnimationActivity.java
  MapboxAndroidDemo/src/main/res/drawable-anydpi/ic_keyboard_arrow_down.xml
  MapboxAndroidDemo/src/main/res/drawable-hdpi/map_marker_push_pin_pink.png
  MapboxAndroidDemo/src/main/res/drawable-mdpi/map_marker_push_pin_pink.png
  MapboxAndroidDemo/src/main/res/drawable-xhdpi/map_marker_push_pin_pink.png
  MapboxAndroidDemo/src/main/res/drawable-xxhdpi/map_marker_push_pin_pink.png
  MapboxAndroidDemo/src/main/res/drawable-xxxhdpi/map_marker_push_pin_pink.png
  MapboxAndroidDemo/src/main/res/layout/activity_animated_pin_drop.xml
  MapboxAndroidDemo/src/main/res/layout/activity_basic_simple_mapview.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
  gradle/dependencies.gradle
Labels: new example :sparkles:, ✓ ready for review :+1:

#1001 Text field anchor position adjustment example
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/RotatingTextAnchorPositionActivity.java
  MapboxAndroidDemo/src/main/res/drawable-anydpi/ic_cycle_through.xml
  MapboxAndroidDemo/src/main/res/layout/activity_dds_style_rotating_text_anchor.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#1010 Refactoring LocationComponent examples to use LocationComponentActivationOptions
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/location/KotlinLocationComponentActivity.kt
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/location/LocationComponentActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/location/LocationComponentFragmentActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/location/LocationComponentOptionsActivity.java
Labels: refactor :recycle:, ✓ ready for review :+1:

#690 Adding reverse geocoding address launcher widget
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/HomeScreenWidgetActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/utils/DemoAppHomeScreenAddressWidget.java
  MapboxAndroidDemo/src/main/res/drawable-hdpi/map_widget_preview_image.png
  MapboxAndroidDemo/src/main/res/drawable-hdpi/mapbox_geocode_widget_preview.png
  MapboxAndroidDemo/src/main/res/drawable-mdpi/map_widget_preview_image.png
  MapboxAndroidDemo/src/main/res/drawable-mdpi/mapbox_geocode_widget_preview.png
  MapboxAndroidDemo/src/main/res/drawable-tvdpi/map_widget_preview_image.png
  MapboxAndroidDemo/src/main/res/drawable-xhdpi/map_widget_preview_image.png
  MapboxAndroidDemo/src/main/res/drawable-xhdpi/mapbox_geocode_widget_preview.png
  MapboxAndroidDemo/src/main/res/drawable-xxhdpi/map_widget_preview_image.png
  MapboxAndroidDemo/src/main/res/drawable-xxhdpi/mapbox_geocode_widget_preview.png
  MapboxAndroidDemo/src/main/res/drawable-xxxhdpi/map_widget_preview_image.png
  MapboxAndroidDemo/src/main/res/drawable-xxxhdpi/mapbox_geocode_widget_preview.png
  MapboxAndroidDemo/src/main/res/layout/activity_homescreen_geocoding_widget.xml
  MapboxAndroidDemo/src/main/res/layout/demo_app_home_screen_widget.xml
  MapboxAndroidDemo/src/main/res/values-v14/dimens.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/dimens.xml
  MapboxAndroidDemo/src/main/res/values/strings.xml
  MapboxAndroidDemo/src/main/res/values/system_and_random_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
  MapboxAndroidDemo/src/main/res/xml/demo_app_home_screen_widget_info.xml
Labels: enhancement :heavy_plus_sign:, new example :sparkles:, ✓ ready for review :+1:

#982 Adding textField color, size, and font adjustment example
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/TextFieldFormattingActivity.java
  MapboxAndroidDemo/src/main/res/drawable/flag_of_egypt.png
  MapboxAndroidDemo/src/main/res/drawable/flag_of_germany.png
  MapboxAndroidDemo/src/main/res/drawable/flag_of_spain.png
  MapboxAndroidDemo/src/main/res/layout/activity_dds_text_field_formatting.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#973 Refactoring of snaking directions route
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/SnakingDirectionsRouteActivity.java
Labels: new example :sparkles:, ✓ ready for review :+1:

#966 Adding polygon click color toggle example [KOTLIN]
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/assets/new-orleans-neighborhoods.geojson
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/PolygonSelectToggleActivity.kt
  MapboxAndroidDemo/src/main/res/layout/activity_dds_polygon_select_toggle.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: kotlin, new example :sparkles:, ✓ ready for review :+1:

#1011 Commit template developer-config.xml
  MapboxAndroidDemo/src/main/res/values/developer-config.xml
Labels: bug :bug:

#1014 Bumped dependencies for new plugin releases
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/SymbolListenerActivity.java
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:

#1017 Using dependencies.gradle file for Gradle plugin script version setup
  gradle/dependencies.gradle
  gradle/gradle-dependencies-graph.gradle
  gradle/script-git-version.gradle
Labels: refactor :recycle:, starter-task

#1016 Tweaks to SymbolLayer iconOffset spacing in InfoWindowSymbolLayerActivity
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/InfoWindowSymbolLayerActivity.java
Labels: refactor :recycle:, ✓ ready for review :+1:

#1035 Bumped Maps SDK to 7.3.2
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:

#987 Adding note about product flavors to README
  README.md
Labels: documentation :memo:, ✓ ready for review :+1:

#1043 Adding SKU generation
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  gradle/dependencies.gradle
Labels: refactor :recycle:, ✓ ready for review :+1:

#1046 Java SDK dependencies bump to 4.7.0
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:
