Repository mapbox/mapbox-android-demo, pull requests merged in 2019-02, with the labels that each got.

#962 license bump to 2019
  license
Labels: ✓ ready for review :+1:

#964 Add data point icon as an SDF in the CircleLayerClusteringActivity
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/CircleLayerClusteringActivity.java
Labels: bug :bug:

#967 Java SDK bump to 4.5.0
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:

#941 Place search SF office address change
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/PlacesPluginActivity.java
Labels: bug :bug:, ✓ ready for review :+1:

#956 Replacing all Log. with Timber
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/BathymetryActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/ChoroplethJsonVectorMixActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/CircleLayerClusteringActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/CreateHotspotsActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/DrawGeojsonLineActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/ExpressionIntegrationActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/ImageClusteringActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/MultipleHeatmapStylingActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/StyleLineIdentityPropertyActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/extrusions/PopulationDensityExtrusionActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/extrusions/RotationExtrusionActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/DirectionsActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/IsochroneActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/MapMatchingActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/MatrixApiActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/OptimizationActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/SimplifyPolylineActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/StaticImageActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/DashedLineDirectionsPickerActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/IndoorMapActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/InsetMapActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/LocationPickerActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/MarkerFollowingRouteActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/SnakingDirectionsRouteActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/SpaceStationLocationActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/offline/OfflineManagerActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/offline/SimpleOfflineMapActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/query/ClickOnLayerActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/query/HighlightedLineActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/ClickToAddImageActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/HillShadeActivity.java
Labels: refactor :recycle:, ✓ ready for review :+1:

#963 Added wearable declaration tag to manifest
  MapboxAndroidDemo/src/main/AndroidManifest.xml
Labels: ✓ ready for review :+1:

#627 Fixing wearable black screen
  MapboxAndroidWearDemo/build.gradle
  MapboxAndroidWearDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/OfflineMapActivity.java
  MapboxAndroidWearDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/SimpleMapViewActivity.java
  MapboxAndroidWearDemo/src/main/res/layout/activity_simple_mapview.xml
  gradle/dependencies.gradle
Labels: bug :bug:, wearable :watch:, ✓ ready for review :+1:

#972 Fix disappearing camera restriction bbox
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/camera/RestrictCameraActivity.java
Labels: bug :bug:, ✓ ready for review :+1:

#979 Removing GIF library
  MapboxAndroidDemo/build.gradle
  MapboxAndroidDemo/src/main/res/drawable-hdpi/pointing_mapbox_astronaut.png
  MapboxAndroidDemo/src/main/res/drawable-hdpi/waving_mapbox_astronaut.png
  MapboxAndroidDemo/src/main/res/drawable-mdpi/pointing_mapbox_astronaut.png
  MapboxAndroidDemo/src/main/res/drawable-mdpi/waving_mapbox_astronaut.png
  MapboxAndroidDemo/src/main/res/drawable-xhdpi/pointing_mapbox_astronaut.png
  MapboxAndroidDemo/src/main/res/drawable-xhdpi/waving_mapbox_astronaut.png
  MapboxAndroidDemo/src/main/res/drawable-xxhdpi/pointing_mapbox_astronaut.png
  MapboxAndroidDemo/src/main/res/drawable-xxhdpi/waving_mapbox_astronaut.png
  MapboxAndroidDemo/src/main/res/drawable-xxxhdpi/pointing_mapbox_astronaut.png
  MapboxAndroidDemo/src/main/res/drawable-xxxhdpi/waving_mapbox_astronaut.png
  MapboxAndroidDemo/src/main/res/layout/activity_landing.xml
  MapboxAndroidDemo/src/main/res/layout/activity_loading.xml
  MapboxAndroidDemo/src/main/res/mipmap-hdpi/mapbox_changing_hands_astronaut.gif
  MapboxAndroidDemo/src/main/res/mipmap-mdpi/mapbox_changing_hands_astronaut.gif
  MapboxAndroidDemo/src/main/res/mipmap-xhdpi/mapbox_changing_hands_astronaut.gif
  MapboxAndroidDemo/src/main/res/mipmap-xxhdpi/mapbox_changing_hands_astronaut.gif
  MapboxAndroidDemo/src/main/res/mipmap-xxxhdpi/mapbox_changing_hands_astronaut.gif
  gradle/dependencies.gradle
Labels: bug :bug:, ✓ ready for review :+1:
