Repository mapbox/mapbox-android-demo, pull requests merged in 2019-03, with the labels that each got.

#980 Added manifest declaration to use CleartextTraffic
  MapboxAndroidDemo/src/main/AndroidManifest.xml
Labels: bug :bug:, ✓ ready for review :+1:

#991 Release 7.2.0
  CHANGELOG.md
  MapboxAndroidDemo/src/global/play/en-US/whatsnew
Labels: ✓ ready for review :+1:

#989 China plugin bump to 2.1.0
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:

#988 Multiple Formats in a Text Field
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/TextFieldMultipleFormatsActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_style_text_field_multiple_formats.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#1000 Add symbol listener activity
  MapboxAndroidDemo/build.gradle
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/SymbolListenerActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_annotation_plugin_symbol_activity.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
  gradle/dependencies.gradle
Labels: new example :sparkles:, work in progress :building_construction:, ✓ ready for review :+1:

#923 Adding ClickToAddImageActivity example to MainActivity
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/MarkerFollowingRouteActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/ClickToAddImageActivity.java
Labels: refactor :recycle:, ✓ ready for review :+1:

#929 Symbol switch based on zoom level example
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/SymbolSwitchOnZoomActivity.java
  MapboxAndroidDemo/src/main/res/drawable-anydpi/ic_person.xml
  MapboxAndroidDemo/src/main/res/layout/activity_zoom_based_icon_switch.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:
