Repository mapbox/mapbox-android-demo, pull requests merged in 2019-07, with the labels that each got.

#1123 RecyclerView + Directions route example
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/RecyclerViewDirectionsActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_lab_recycler_view_directions.xml
  MapboxAndroidDemo/src/main/res/layout/rv_directions_card.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#1127 Add tutorial demos
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/CircleRadiusActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/location/LocationChangeListeningActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/RuntimeStylingActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_circle_radius_activity.xml
  MapboxAndroidDemo/src/main/res/layout/activity_location_change_listening.xml
  MapboxAndroidDemo/src/main/res/layout/activity_styles_runtime_styling.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:

#1140 Adding kotlin lint plugin and needed tweaks
  Makefile
  MapboxAndroidDemo/build.gradle
  MapboxAndroidDemo/src/china/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/basics/KotlinSimpleMapViewActivity.kt
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/KotlinStyleCirclesCategoricallyActivity.kt
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/PolygonSelectToggleActivity.kt
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/MagicWindowKotlinActivity.kt
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/location/KotlinLocationComponentActivity.kt
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/model/ExampleItemModel.kt
  MapboxAndroidDemo/src/main/res/layout/activity_basic_simple_kotlin.xml
  build.gradle
  gradle/dependencies.gradle
Labels: refactor :recycle:, ✓ ready for review :+1:

#1145 Polygon hole layer below null check
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/PolygonHolesActivity.java
Labels: ✓ ready for review :+1:

#1047 Define a Circle's Radius with Physical Units
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/TurfPhysicalCircleActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_lab_turf_circle_physical_units.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#1149 Adjusted manifest to fix SimpleMapView kotlin example
  MapboxAndroidDemo/src/main/AndroidManifest.xml
Labels: crash :boom:, refactor :recycle:, ✓ ready for review :+1:

#1148 Refactor QueryFeatureActivity to use SymbolLayer instead of MarkerViewOptions
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/query/QueryFeatureActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_query_feature_window_symbol_layer.xml
Labels: refactor :recycle:, ✓ ready for review :+1:

#1150 Refactoring GeoJsonSource creation with URL to URI
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/CircleLayerClusteringActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/CreateHotspotsActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/HeatmapActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/ImageClusteringActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/query/ClickOnLayerActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/GeojsonLayerInStackActivity.java
Labels: refactor :recycle:

#1154 Scalebar Plugin bump to 0.2.0
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:
