Repository mapbox/mapbox-android-demo, pull requests merged in 2019-11, with the labels that each got.

#1258 Commented out PlaceSelectionPluginActivity place picker example
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
Labels: crash :boom:, refactor :recycle:, ✓ ready for review :+1:

#1260 Updates WMS source example to fix missing 3rd party satellite imagery
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/AddWmsSourceActivity.java
Labels: bug :bug:, refactor :recycle:, ✓ ready for review :+1:

#1246 Maps SDK to v8.5.0 update
  gradle/dependencies.gradle
Labels: :warning: DO NOT MERGE :warning:

#1266 China plugin dependency bump to 2.4.0
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:

#1265 Release 8.5.0
  CHANGELOG.md
  MapboxAndroidDemo/src/global/play/release-notes/en-US/default.txt
Labels: ✓ ready for review :+1:

#1267 Adding example of loading China or global style based on device location
  MapboxAndroidDemo/src/china/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/china/java/com/mapbox/mapboxandroiddemo/examples/ChinaBoundsCheckerActivity.kt
  MapboxAndroidDemo/src/china/java/com/mapbox/mapboxandroiddemo/examples/MixedChinaAndGlobalStyleActivity.kt
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#1270 Disabling collision transition for clustering examples
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/CircleLayerClusteringActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/ImageClusteringActivity.java
Labels: refactor :recycle:

#1272 Adding fingerprint biometric authentication example
  MapboxAndroidDemo/build.gradle
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/BiometricFingerprintLayerUnlockActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/BasicSymbolLayerActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_labs_biometric_fingerprint.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
  gradle/dependencies.gradle
Labels: new example :sparkles:, ✓ ready for review :+1:
