Repository mapbox/mapbox-android-demo, pull requests merged in 2019-08, with the labels that each got.

#1155 Bumped Maps SDK to 8.2.1
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:

#1139 Adding example of cache management methods usage
  .gitignore
  MapboxAndroidDemo/build.gradle
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MapboxApplication.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/basics/SimpleMapViewActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/IsochroneSeekbarActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/offline/CacheManagementActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/utils/CustomFirebaseMessagingService.java
  MapboxAndroidDemo/src/main/res/layout/activity_offline_cache_manipulation.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
  MapboxAndroidDemo/src/main/res/xml/cache_management_remote_config_defaults.xml
  MapboxAndroidWearDemo/build.gradle
  MapboxAndroidWearDemo/src/main/res/layout/activity_simple_mapview.xml
  circle.yml
  gradle/dependencies.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ✓ ready for review :+1:

#1162 Release 8.2.1
  CHANGELOG.md
  MapboxAndroidDemo/src/global/play/en-US/whatsnew
Labels: ✓ ready for review :+1:

#1166 Added CircleCI command to create google services json file in Release job
  circle.yml
Labels: refactor :recycle:

#1167 Added hyperlinks to changelog lines
  CHANGELOG.md
Labels: refactor :recycle:, starter-task

#1171 Downgraded gradle version to 3.3.0
  gradle/dependencies.gradle
Labels: refactor :recycle:

#1173 Switched `ImageClusteringActivity` filter use to gte
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/ImageClusteringActivity.java
Labels: refactor :recycle:, ✓ ready for review :+1:

#1175 Bumped localization plugin to 0.11.0
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:

#1176 Bumped Scale Bar Plugin to 0.3.0
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:

#1177 Adding spinning SymbolLayer icons example
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/assets/spinning_icon.geojson
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/SpinningSymbolLayerIconActivity.java
  MapboxAndroidDemo/src/main/res/drawable/hurricane_icon.xml
  MapboxAndroidDemo/src/main/res/layout/activity_spinning_symbol_layer_icon.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#1179 Refactoring changes to switch loadGeoJsonFromAsset() usage to URI
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/BathymetryActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/MultipleGeometriesActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/MultipleHeatmapStylingActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/StyleLineIdentityPropertyActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/extrusions/Indoor3DMapActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/extrusions/MarathonExtrusionActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/query/HighlightedLineActivity.java
Labels: refactor :recycle:, ✓ ready for review :+1:

#1161 Maps SDK to v8.3.0 update
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:
