Repository mapbox/mapbox-android-demo, pull requests merged in 2020-05, with the labels that each got.

#1340 Added within POI circle polygon filter example
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/IsochroneSeekbarActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/TurfCirclePoiWithinFilterActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/TurfPhysicalCircleActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_lab_turf_circle_poi_within_filter.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#1339 Added two person isochrone POIs within expression filter example
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/TwoPersonMeetupLocationIsochroneWithinActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_javaservices_two_person_isochrone_poi_meetup.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#1341 Added 3d extrusions zoom-based opacity example
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/extrusions/OpacityZoomChangeExtrusionKotlinActivity.kt
  MapboxAndroidDemo/src/main/res/layout/activity_zoom_opacity_extrusion.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#1330 Added vibrate device on pin drop example
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/VibrateOnPinDropKotlinActivity.kt
  MapboxAndroidDemo/src/main/res/layout/activity_lab_vibrate_on_pin_drop_kotlin.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#1345 Java SDK bump to 5.2.0
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:

#1344 Added pulsing LocationComponent examples
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/location/LocationComponentBasicPulsingActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/location/LocationComponentCustomPulsingActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_location_component.xml
  MapboxAndroidDemo/src/main/res/layout/activity_location_component_custom_pulsing.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#1346 Java SDK bump to 5.2.1
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:

#1348 Release 9.2.0
  CHANGELOG.md
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/global/play/release-notes/en-US/default.txt
Labels: ✓ ready for review :+1:

#1349 Updated gradle options in circle.yml file
  circle.yml
Labels: ✓ ready for review :+1:

#1350 Fixed location of MixedChinaAndGlobalStyleActivity token toast message
  MapboxAndroidDemo/src/china/java/com/mapbox/mapboxandroiddemo/examples/MixedChinaAndGlobalStyleActivity.kt
Labels: refactor :recycle:, ✓ ready for review :+1:

#1351 Added Mapbox token initialization to PlaceSelectionPluginActivity
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/PlaceSelectionPluginActivity.java
Labels: bug :bug:, ✓ ready for review :+1:

#1298 Fixed source and layer name for ImageSourceActivity
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/ImageSourceActivity.java
Labels: refactor :recycle:, ✓ ready for review :+1:

#1310 Light cleanup of FeatureCollection and Source initialization
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/DashedLineDirectionsPickerActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/RecyclerViewOnMapActivity.java
Labels: refactor :recycle:, ✓ ready for review :+1:

#1352 Added feature list size check in PolygonSelectToggleActivity
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/PolygonSelectToggleActivity.kt
Labels: bug :bug:, ✓ ready for review :+1:

#1353 Use default marker icon
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/BasicSymbolLayerActivity.java
Labels: refactor :recycle:, ✓ ready for review :+1:
