Repository mapbox/mapbox-android-demo, pull requests merged in 2020-01, with the labels that each got.

#1282 Bumped Maps SDK to 8.6.0
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:

#1286 Release 8.6.0
  CHANGELOG.md
  MapboxAndroidDemo/src/global/play/release-notes/en-US/default.txt
Labels: ✓ ready for review :+1:

#1287 Bumped Java SDK to 5.0.0
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/ElevationQueryActivity.java
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/TilequeryActivity.java
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:

#1288 Fix typo in SpaceStationLocationActivity comment
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/SpaceStationLocationActivity.java
Labels: ✓ ready for review :+1:

#1290 Added example of SymbolLayer icon being set based on property
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/PropertyIconDeterminationActivity.java
  MapboxAndroidDemo/src/main/res/drawable-xxhdpi/yellow_marker.png
  MapboxAndroidDemo/src/main/res/layout/activity_dds_property_icon_switch.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:

#1289 Adding straight line Turf distance measurement ("as the crow flies") example
  MapboxAndroidDemo/src/global/java/com/mapbox/mapboxandroiddemo/MainActivity.java
  MapboxAndroidDemo/src/main/AndroidManifest.xml
  MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/StraightLineDistanceMapMovementActivity.java
  MapboxAndroidDemo/src/main/res/layout/activity_javaservices_straight_line_distance.xml
  MapboxAndroidDemo/src/main/res/values/activity_strings.xml
  MapboxAndroidDemo/src/main/res/values/descriptions_strings.xml
  MapboxAndroidDemo/src/main/res/values/titles_strings.xml
  MapboxAndroidDemo/src/main/res/values/urls_strings.xml
Labels: new example :sparkles:, ✓ ready for review :+1:

#1291 Bumped maps sdk to 8.6.2
  gradle/dependencies.gradle
Labels: ✓ ready for review :+1:
